project:
  title: "Enhancing Artificial Data for the NHP Model"
  output-dir: docs
  resources:
    - docs/images/

format:
  html:
    theme:
      light: [default, su_presentation.scss]
    toc: true